#!/usr/bin/Rscript

"rworker - R consumer for Message Brokers  
Usage: rworker.R TASKFILE [--provider=<PROV> --queue=<QUEUE> --host=<ADDR> --port=<PORT> --workers=<WORKERS> --verbose]

Input:
  TASKFILE                         file containing your tasks (functions)
Options:
  -h --help                         show this help message
  --version                         show program version
  -r --provider=<PROV>              Message Broker Provider [default: redis]
  -q --queue=<QUEUE>                Queue name [default: queue]
  -r --host=<ADDR>                  Message Broker instance address [default: localhost]
  -p --port=<PORT>                  Message Broker port [default: 6379]
  -w --workers=<WORKERS>            number of worker processes [default: 1]
  -v --verbose                      display task execution
Author:
  Lucas E Cardozo - lucas.cardozo at usp.br
" -> doc

suppressMessages({
    library(rworker) 
})

arg <- docopt(doc, version="0.0.1\n", strict=TRUE)
arg <- arg[!sapply(arg, is.null)][-(1:2)]  # filter missing, 'help' and 'version'
clean <- function(s) gsub('-', '_', gsub('^-+', '', tolower(s)))
names(arg) <- clean(names(arg))

tasks <- rworker::Tasks$new(src=arg[['taskfile']])

queue <- rworker::Queue$new(provider=arg[['provider']],
                            host=arg[['host']],
                            port=arg[['port']],
                            name=arg[['queue']])

consumer <- rworker::Consumer$new(queue=queue, tasks=tasks,
                                  nworkers=as.numeric(args[['workers']]))

consumer$consume()
